### ISSUE TITLE
Add more usage information and documentation

### ISSUE THREAD

**Issue by yuliannabn** [migalabs/ragno#32]
# Tasks
Add and elaborate on the following details:

- [ ] How to use migrate
- [ ] How to run with docker
- [ ] Mention cloning with submodules/recursive
- [ ] Info about Prometheus metrics
- [ ] Info about table columns (perhaps add in docs?)
- [ ] Info about `ip-api.com` used for the `ip_info` table
